/**
 * Canonical error codes used throughout the Huefy SDK.
 *
 * Each member carries a human-readable string value for serialisation
 * and logging.  A companion numeric code map is provided for systems
 * that require integer identifiers.
 */
export enum ErrorCode {
  // Initialisation
  INIT_FAILED = 'INIT_FAILED',
  INIT_TIMEOUT = 'INIT_TIMEOUT',

  // Authentication
  API_KEY_REQUIRED = 'API_KEY_REQUIRED',
  API_KEY_INVALID = 'API_KEY_INVALID',
  API_KEY_EXPIRED = 'API_KEY_EXPIRED',
  API_KEY_SUSPENDED = 'API_KEY_SUSPENDED',
  PROJECT_ACCESS_DENIED = 'PROJECT_ACCESS_DENIED',
  AUTH_INVALID_KEY = 'AUTH_INVALID_KEY',
  AUTH_EXPIRED_KEY = 'AUTH_EXPIRED_KEY',
  AUTH_MISSING_KEY = 'AUTH_MISSING_KEY',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',

  // Network
  NETWORK_ERROR = 'NETWORK_ERROR',
  NETWORK_TIMEOUT = 'NETWORK_TIMEOUT',
  NETWORK_RETRY_LIMIT = 'NETWORK_RETRY_LIMIT',
  NETWORK_SERVICE_UNAVAILABLE = 'NETWORK_SERVICE_UNAVAILABLE',

  // Circuit breaker
  CIRCUIT_OPEN = 'CIRCUIT_OPEN',

  // Configuration
  CONFIG_INVALID_URL = 'CONFIG_INVALID_URL',
  CONFIG_MISSING_REQUIRED = 'CONFIG_MISSING_REQUIRED',

  // Security
  SECURITY_PII_DETECTED = 'SECURITY_PII_DETECTED',
  SECURITY_SIGNATURE_INVALID = 'SECURITY_SIGNATURE_INVALID',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_REQUEST = 'INVALID_REQUEST',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  INVALID_FIELD_VALUE = 'INVALID_FIELD_VALUE',
  REQUEST_TOO_LARGE = 'REQUEST_TOO_LARGE',
  IDEMPOTENCY_IN_PROGRESS = 'IDEMPOTENCY_IN_PROGRESS',

  // Billing / quota
  INSUFFICIENT_QUOTA = 'INSUFFICIENT_QUOTA',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  DAILY_LIMIT_EXCEEDED = 'DAILY_LIMIT_EXCEEDED',
  MONTHLY_LIMIT_EXCEEDED = 'MONTHLY_LIMIT_EXCEEDED',

  // Template
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  TEMPLATE_NOT_PUBLISHED = 'TEMPLATE_NOT_PUBLISHED',
  TEMPLATE_VERSION_NOT_FOUND = 'TEMPLATE_VERSION_NOT_FOUND',
  TEMPLATE_RENDER_FAILED = 'TEMPLATE_RENDER_FAILED',
  INVALID_TEMPLATE_DATA = 'INVALID_TEMPLATE_DATA',
  TEMPLATE_ACCESS_DENIED = 'TEMPLATE_ACCESS_DENIED',

  // Email
  INVALID_EMAIL = 'INVALID_EMAIL',
  EMAIL_SUPPRESSED = 'EMAIL_SUPPRESSED',
  INVALID_SENDER = 'INVALID_SENDER',
  SENDER_NOT_VERIFIED = 'SENDER_NOT_VERIFIED',
  RECIPIENT_LIMIT_EXCEEDED = 'RECIPIENT_LIMIT_EXCEEDED',

  // Provider
  PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE',
  PROVIDER_CONFIG_ERROR = 'PROVIDER_CONFIG_ERROR',
  SEND_FAILED = 'SEND_FAILED',
  PROVIDER_RATE_LIMIT = 'PROVIDER_RATE_LIMIT',

  // System
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR = 'DATABASE_ERROR',
  TIMEOUT_ERROR = 'TIMEOUT_ERROR',
}

/**
 * Maps each {@link ErrorCode} to a stable numeric identifier.
 */
export const numericCodeMap: Record<ErrorCode, number> = {
  [ErrorCode.INIT_FAILED]: 1000,
  [ErrorCode.INIT_TIMEOUT]: 1001,

  [ErrorCode.API_KEY_REQUIRED]: 1000,
  [ErrorCode.API_KEY_INVALID]: 1001,
  [ErrorCode.API_KEY_EXPIRED]: 1002,
  [ErrorCode.API_KEY_SUSPENDED]: 1003,
  [ErrorCode.PROJECT_ACCESS_DENIED]: 1005,
  [ErrorCode.AUTH_INVALID_KEY]: 1100,
  [ErrorCode.AUTH_EXPIRED_KEY]: 1101,
  [ErrorCode.AUTH_MISSING_KEY]: 1102,
  [ErrorCode.AUTH_UNAUTHORIZED]: 1103,

  [ErrorCode.NETWORK_ERROR]: 1200,
  [ErrorCode.NETWORK_TIMEOUT]: 1201,
  [ErrorCode.NETWORK_RETRY_LIMIT]: 1202,
  [ErrorCode.NETWORK_SERVICE_UNAVAILABLE]: 1203,

  [ErrorCode.CIRCUIT_OPEN]: 1300,

  [ErrorCode.CONFIG_INVALID_URL]: 1400,
  [ErrorCode.CONFIG_MISSING_REQUIRED]: 1401,

  [ErrorCode.SECURITY_PII_DETECTED]: 1500,
  [ErrorCode.SECURITY_SIGNATURE_INVALID]: 1501,

  [ErrorCode.VALIDATION_ERROR]: 1600,
  [ErrorCode.INVALID_REQUEST]: 1500,
  [ErrorCode.MISSING_REQUIRED_FIELD]: 1501,
  [ErrorCode.INVALID_FIELD_VALUE]: 1502,
  [ErrorCode.REQUEST_TOO_LARGE]: 1503,
  [ErrorCode.IDEMPOTENCY_IN_PROGRESS]: 1504,

  [ErrorCode.INSUFFICIENT_QUOTA]: 1004,
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 1100,
  [ErrorCode.DAILY_LIMIT_EXCEEDED]: 1101,
  [ErrorCode.MONTHLY_LIMIT_EXCEEDED]: 1102,

  [ErrorCode.TEMPLATE_NOT_FOUND]: 1200,
  [ErrorCode.TEMPLATE_NOT_PUBLISHED]: 1201,
  [ErrorCode.TEMPLATE_VERSION_NOT_FOUND]: 1202,
  [ErrorCode.TEMPLATE_RENDER_FAILED]: 1203,
  [ErrorCode.INVALID_TEMPLATE_DATA]: 1204,
  [ErrorCode.TEMPLATE_ACCESS_DENIED]: 1205,

  [ErrorCode.INVALID_EMAIL]: 1300,
  [ErrorCode.EMAIL_SUPPRESSED]: 1301,
  [ErrorCode.INVALID_SENDER]: 1302,
  [ErrorCode.SENDER_NOT_VERIFIED]: 1303,
  [ErrorCode.RECIPIENT_LIMIT_EXCEEDED]: 1304,

  [ErrorCode.PROVIDER_UNAVAILABLE]: 1400,
  [ErrorCode.PROVIDER_CONFIG_ERROR]: 1401,
  [ErrorCode.SEND_FAILED]: 1402,
  [ErrorCode.PROVIDER_RATE_LIMIT]: 1403,

  [ErrorCode.INTERNAL_ERROR]: 1600,
  [ErrorCode.SERVICE_UNAVAILABLE]: 1601,
  [ErrorCode.DATABASE_ERROR]: 1602,
  [ErrorCode.TIMEOUT_ERROR]: 1603,
};

/**
 * Returns the numeric code for a given {@link ErrorCode}.
 */
export function getNumericCode(code: ErrorCode): number {
  return numericCodeMap[code];
}

/** Set of error codes that represent transient / recoverable failures. */
const RECOVERABLE_CODES: ReadonlySet<ErrorCode> = new Set<ErrorCode>([
  ErrorCode.NETWORK_ERROR,
  ErrorCode.NETWORK_TIMEOUT,
  ErrorCode.NETWORK_RETRY_LIMIT,
  ErrorCode.NETWORK_SERVICE_UNAVAILABLE,
  ErrorCode.CIRCUIT_OPEN,
  ErrorCode.RATE_LIMIT_EXCEEDED,
  ErrorCode.PROVIDER_UNAVAILABLE,
  ErrorCode.PROVIDER_RATE_LIMIT,
  ErrorCode.SERVICE_UNAVAILABLE,
  ErrorCode.TIMEOUT_ERROR,
  ErrorCode.INTERNAL_ERROR,
  ErrorCode.DATABASE_ERROR,
]);

/**
 * Returns `true` when the given error code represents a transient failure
 * that may succeed on retry.
 */
export function isRecoverableCode(code: ErrorCode): boolean {
  return RECOVERABLE_CODES.has(code);
}
